### ISSUE TITLE
Bracket colors

### ISSUE THREAD

**Issue by behzade** [mvpopuk/inspired-github.vim#4]
Currently the bracket under the cursor and the matching bracket have the same highlight color and it can sometimes be confusing. It would be great if they were slightly different.

**Comment by mvpopuk** [comment]
> Currently the bracket under the cursor and the matching bracket have the same highlight color and it can sometimes be confusing. It would be great if they were slightly different.

Fixed with commit [92583a0](https://github.com/mvpopuk/inspired-github.vim/commit/92583a08c59a1fecffbf17c1a967bc2b1ab6ada0). Thanks!
