### ISSUE TITLE
Move images in screenshots folder to issues

### ISSUE THREAD

**Issue by younger-1** [mvpopuk/inspired-github.vim#5]
This can reduce the repo size significantly

**Comment by mvpopuk** [comment]
<img width="982" alt="php" src="https://user-images.githubusercontent.com/35864222/162174274-59b2d412-5d47-408e-923b-b950302e84a3.png">

**Comment by mvpopuk** [comment]
<img width="980" alt="blade" src="https://user-images.githubusercontent.com/35864222/162174351-8bbdd7c8-3c8a-4b4e-8d3b-0c69938dc49d.png">

**Comment by mvpopuk** [comment]
<img width="981" alt="vue" src="https://user-images.githubusercontent.com/35864222/162174425-5b16d3fe-eaca-49ce-ac3b-11d680d1340c.png">

**Comment by mvpopuk** [comment]
<img width="980" alt="css" src="https://user-images.githubusercontent.com/35864222/162174479-5e59ebca-bcbb-4276-86de-12d0ae950450.png">

**Comment by mvpopuk** [comment]
<img width="913" alt="lualine" src="https://user-images.githubusercontent.com/35864222/162174549-62664d79-8d7a-4e6d-be65-c2ab59e3f0fd.png">

**Comment by mvpopuk** [comment]
<img width="914" alt="tmux" src="https://user-images.githubusercontent.com/35864222/162174573-d5e79abc-79c4-468c-874b-8bea2d875b99.png">
